### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#153]
I'm still struggling with how to properly explain the idea behind the project.
The last attempt can be found under https://www.worlddriven.org/ or in the `index.html`, reviewing this and improving (not only the english) would be a huge help.

**Comment by IanFindlay** [comment]
I could certainly proofread this and make some changes for you. As far as explaining the idea, I think you've done that fairly well. Unless I am mistaken it is a:

Kind of like a democratic means of managing PRs. The merge is automated but there is a scaling time-window until it does it. This window is affected by the commit itself, more complicated (more commits in the PR) merges take longer to auto-merge and also by a voting system that uses the reviewing feature. 

The only thing I am not sure about is how the voting system works i.e. how does one express a preference in a review that the request is good vs bad?

If you think I've got the gist the of it, I am happy to get cracking on the changes. As a side-note, I think this is a rather interesting idea.

**Comment by TooAngel** [comment]
:-) Thanks

You got the idea, just some extensions: The voting is weighted based on the commits which you have already on the repository. So if you have already contributed a lot, you have the 'power' the increase the time the merge by a lot.

Voting is done by using the github review feature: 'Approve' is voting yes, 'Request changes' is voting no.

I already tried to improve the documentation in this PR https://github.com/TooAngel/worlddriven/pull/149 - which tries to explain the idea in three phases, because there is more than just the auto-merge.

So this would be a good start and should be merged soonish :-)
