### ISSUE TITLE
Docker / docker-compose setup

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#160]
To ease up the development environment a container setup would be nice.

The service is using mongodb as a backend, so having a container for that is necessary => docker-compose

For login the service also talks to the github API, best would be if this could be mocked somehow, too (as a bonus)

**Comment by eriksape** [comment]
can i help?

**Comment by TooAngel** [comment]
Sure :-)

It would be cool for development if the project could be started by something like `docker-compose up`. For the application itself, it needs python, as backend a mongodb container. 
The mongourl can be set as environment variable via: `MONGODB_URI`

The server is started via `gunicorn` you can checkout the `Procfile` or my just updated README https://github.com/TooAngel/worlddriven/pull/163

Let me know if you have any questions.
