### ISSUE TITLE
Change from draft to open

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#161]
Currently, only the Pull Request open date, the commit date and the latest push (pull request update) date is taken in account.

To trick in a Pull Request you can open a Draft PR, wait the time to merge and change to open and it will be merged directly.

=> For the calculations the date when a PR is changed to open needs to be included.

**Comment by tomsajuk** [comment]
Hi @TooAngel I would like to try this out. Can I?

**Comment by TooAngel** [comment]
Cool, sure, go ahead, let us know when you have questions
