### ISSUE TITLE
New Review message buggy

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#162]
The Pull Request comment when someone reviews a Pull Request is wrong: (https://github.com/TooAngel/worlddriven/pull/159)

`Check the `worlddriven` status checks or the [dashboard](https://www.worlddriven.org/TooAngel/worlddriven/pull/159) for actual stats.` - shouldn't be formatted as code.

The time calculation does not count in the current review. I think the underlying is:
The message is triggered by the github webhook `Pull_Request_Review`, within that requests the reviews are fetched and the current one is not yet included.
Solution: Extract the necessary data out of the webhook data and include it in the calculations.

**Comment by bitshiftsdotio** [comment]
Mind if I pick this up?
