### ISSUE TITLE
Update HTML line breaks to paragraph tags

### ISSUE THREAD

**Issue by IanFindlay** [TooAngel/worlddriven#168]
Modern HTML design uses \<p\> tags instead of \<br /> for line breaks. Updating all of the static files in this way should make further styling to the pages easier.

**Comment by IanFindlay** [comment]
I'm working on this now. @TooAngel you can assign it to me / add some tags to it if you like, I think I am unable to do it as a Contributor.

**Comment by TooAngel** [comment]
Well, actually in the first place me tagging or assigning issues is not in the sense of the world driven idea. But it helped already :-)
But it brings the question of how to handle assigning and labeling of issues in a worlddriven manner. I opened an issue for that: #170, maybe we can come up with something funny.
