### ISSUE TITLE
Post-review worlddrivenbot message doesn't mention the hours until merge

### ISSUE THREAD

**Issue by IanFindlay** [TooAngel/worlddriven#172]
I noticed that the post-review message from worlddrivenbot only mentions the days until merge not the hours. I think adding the hours is a good idea.

I believe this section is the one that need updating: https://github.com/TooAngel/worlddriven/blob/cc450b37884b35eb2a6928e29ca8e25b6444f024/src/routes/githubWebHook.py#L139-L143

The hours can be calculated the same way as it is above, i.e `math.floor(pr.days_to_merge.seconds / 3600)`, but we can also get rid of the math import by using `pr.days_to_merge.seconds // 3600` instead.

Any thoughts?

**Comment by TooAngel** [comment]
I think this is a good idea.

On a side note, currently, the merge is triggered at the end of each hour and not exactly on the calculated merge datetime. Getting more exact than hours wouldn't make more sense right now, without touching the merge logic.
