### ISSUE TITLE
Include new logo into the frontpage and adapt according

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#174]
Recently a new logo was proposed and merged (`/static/images/[favicon-16x16.png, favicon-32x32.png, globe_logo.svg, logo_world_driven.svg]`), these need to be used on the frontpage (`/static/index.html`). .
The style/colors should be adapted to the color palette https://user-images.githubusercontent.com/44964878/94834270-755dc700-0410-11eb-9b8f-b78775ba4cc9.png

**Comment by zbarovsky** [comment]
Hi! I'd like to tackle this if it's still available?

**Comment by Rasikamurali** [comment]
Hello, I'd like to work on this if available.

**Comment by TooAngel** [comment]
Yes, it's still available, go ahead
