### ISSUE TITLE
Change the database backend

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#192]
The current MongoDB provider mLab will shutdown by 2020-11-01. Another MongoDB addon provider needs to be choose and the database needs to be migrated.

## How (I would sketch right now how) it should be done for a real World Driven service

The add-on configuration is somewhere stored in the repository (maybe `app.json`).
A new Pull Request is created adding the new addon. When this is merged the CI server will read that config file and provisions the new database

A second Pull Request is created indicates that the data needs to be migrated and the system should use the new database afterward. (Maybe with a maintenance page in between, would be cool if we don have to)

A third Pull Request removes the old database and the CI server will make sure the database is removed.

## How I would do it now

Yeah, do it manually. (If someone is interested in preparing the proper process, we could do the first steps)

**Comment by TooAngel** [comment]
Heroku does not provide any free MongoDB addon. The smallest plan ist 46$/month, which I don't want to spend for a pet project right now.
I added the JawsDB Maria addon and will change the database backend from MongoDB to MariaDB.

**Comment by IanFindlay** [comment]
Sounds great to me. I've been putting off installing MongoDB as I run Arch and it has been removed from official repositories whereas MariaDB is the default MySQL.
