### ISSUE TITLE
Encrypt the github tokens in the database

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/worlddriven#197]
The github keys currently are stored in plain text in the database. To make sure these are not accessible if someone gets access to the database, the keys needs to be encrypted with a secret which is available in the application via environment variable.

**Comment by EANimesha** [comment]
Can I try this?

**Comment by TooAngel** [comment]
Yeah, sure go ahead.

Let me know if you have any questions.

**Comment by TooAngel** [comment]
Hey, were you able to make any progress, can I help somehow?

**Comment by EANimesha** [comment]
> Hey, were you able to make any progress, can I help somehow?

couldn't able  to make a progress
